/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.StateGovernor;

import BLL.EcoSystem;
import BLL.Enterprise.Enterprise;
import BLL.Network.Network;
import BLL.Person.Person;
import BLL.Person.VitalSign;
import BLL.Role.HealthcareAdmin;
import BLL.Role.ResidentAdmin;
import BLL.Role.Role;
import BLL.Role.TrafficAdmin;
import BLL.Role.WeatherReporter;
import BLL.UserAccount.UserAccount;
import static UI.SmartDriveMain.validator;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankur
 */
public class ManageEnterprisePanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterprisePanel
     */
    private EcoSystem system;
    public ManageEnterprisePanel(EcoSystem system) {
        initComponents();
        this.system = system;
        
        populateTable();
        populateComboBox();
        
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                int flag=0;
                for(UserAccount userAccount: enterprise.getUserAccountDirectory().getUserAccountList())
                {
                    Object[] row = new Object[4];
                    row[0] = network.getName();
                    row[1] = enterprise.getName();
                    row[2] = enterprise.getEnterpriseType().getValue();
                    row[3] = userAccount.getPerson();
                    model.addRow(row);
                    flag=1;
                }
                if(flag==0)
                {
                    Object[] row = new Object[4];
                    row[0] = network.getName();
                    row[1] = enterprise.getName();
                    row[2] = enterprise.getEnterpriseType().getValue();
                    model.addRow(row);
                }
            }
        }
    }

    private void populateComboBox() {
        networkJComboBox.removeAllItems();
        enterpriseTypeJComboBox.removeAllItems();
        
        networkJComboBox1.removeAllItems();

        for (Network network : system.getNetworkList()) {
            networkJComboBox.addItem(network);
            networkJComboBox1.addItem(network);
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            enterpriseTypeJComboBox.addItem(type);
        }

    }
    private void populateEnterpriseComboBox(Network network){
        enterpriseJComboBox.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            enterpriseJComboBox.addItem(enterprise);
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        verticalEnterpriseSplitPane = new javax.swing.JSplitPane();
        newEnterprisePanel = new javax.swing.JPanel();
        newEnterpriseLabel = new javax.swing.JLabel();
        selectNetworkLbl = new javax.swing.JLabel();
        enterpriseTypeLbl = new javax.swing.JLabel();
        enterpriseNameLbl = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        enterpriseTypeJComboBox = new javax.swing.JComboBox();
        nameJTextField = new javax.swing.JTextField();
        addEnterpriseBtn = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        addEnterpriseAdminPanel = new javax.swing.JPanel();
        newEnterpriseLabel1 = new javax.swing.JLabel();
        selectNetworkLbl1 = new javax.swing.JLabel();
        networkJComboBox1 = new javax.swing.JComboBox();
        enterpriseTypeLbl1 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        enterpriseNameLbl1 = new javax.swing.JLabel();
        adminNameTextfield = new javax.swing.JTextField();
        addEnterpriseAdminBtn = new javax.swing.JButton();
        enterpriseNameLbl2 = new javax.swing.JLabel();
        usernameTextfield = new javax.swing.JTextField();
        enterpriseNameLbl3 = new javax.swing.JLabel();
        passwordTextfield = new javax.swing.JPasswordField();
        warningLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        enterpriseJTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Network", "Enterprise Name", "Enterprise Type", "Enterprise Admin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);

        verticalEnterpriseSplitPane.setDividerLocation(260);
        verticalEnterpriseSplitPane.setDividerSize(2);
        verticalEnterpriseSplitPane.setResizeWeight(0.5);

        newEnterprisePanel.setBackground(new java.awt.Color(255, 255, 255));

        newEnterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newEnterpriseLabel.setText("Add new Enterprise");

        selectNetworkLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selectNetworkLbl.setText("Select Network:");

        enterpriseTypeLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterpriseTypeLbl.setText("Enterprise Type:");

        enterpriseNameLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterpriseNameLbl.setText("Enterprise Name:");

        networkJComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        enterpriseTypeJComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nameJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedToNameTextfield(evt);
            }
        });

        addEnterpriseBtn.setBackground(new java.awt.Color(255, 255, 255));
        addEnterpriseBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addEnterpriseBtn.setForeground(new java.awt.Color(0, 102, 153));
        addEnterpriseBtn.setText("Add Enterprise");
        addEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseBtnActionPerformed(evt);
            }
        });

        warningLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout newEnterprisePanelLayout = new javax.swing.GroupLayout(newEnterprisePanel);
        newEnterprisePanel.setLayout(newEnterprisePanelLayout);
        newEnterprisePanelLayout.setHorizontalGroup(
            newEnterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEnterprisePanelLayout.createSequentialGroup()
                .addGroup(newEnterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newEnterprisePanelLayout.createSequentialGroup()
                        .addGroup(newEnterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newEnterprisePanelLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(newEnterpriseLabel))
                            .addGroup(newEnterprisePanelLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(addEnterpriseBtn))
                            .addGroup(newEnterprisePanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(newEnterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(newEnterprisePanelLayout.createSequentialGroup()
                                        .addComponent(enterpriseTypeLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(enterpriseTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(newEnterprisePanelLayout.createSequentialGroup()
                                        .addComponent(selectNetworkLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(newEnterprisePanelLayout.createSequentialGroup()
                                        .addComponent(enterpriseNameLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newEnterprisePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        newEnterprisePanelLayout.setVerticalGroup(
            newEnterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEnterprisePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newEnterpriseLabel)
                .addGap(18, 18, 18)
                .addGroup(newEnterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectNetworkLbl)
                    .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(newEnterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseTypeLbl)
                    .addComponent(enterpriseTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(newEnterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseNameLbl)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(addEnterpriseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        verticalEnterpriseSplitPane.setLeftComponent(newEnterprisePanel);

        addEnterpriseAdminPanel.setBackground(new java.awt.Color(255, 255, 255));

        newEnterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newEnterpriseLabel1.setText("Add Admin to Enterprise");

        selectNetworkLbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selectNetworkLbl1.setText("Select Network:");

        networkJComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        networkJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBoxSelected(evt);
            }
        });

        enterpriseTypeLbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterpriseTypeLbl1.setText("Select Enterprise:");

        enterpriseJComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        enterpriseNameLbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterpriseNameLbl1.setText("Admin Name:");

        adminNameTextfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        adminNameTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedToAddAdminTextfields(evt);
            }
        });

        addEnterpriseAdminBtn.setBackground(new java.awt.Color(255, 255, 255));
        addEnterpriseAdminBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addEnterpriseAdminBtn.setForeground(new java.awt.Color(0, 102, 153));
        addEnterpriseAdminBtn.setText("Submit");
        addEnterpriseAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseAdminBtnActionPerformed(evt);
            }
        });

        enterpriseNameLbl2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterpriseNameLbl2.setText("Username:");

        usernameTextfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedToAddAdminTextfields(evt);
            }
        });

        enterpriseNameLbl3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterpriseNameLbl3.setText("Password:");

        passwordTextfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusGainedToAddAdminTextfields(evt);
            }
        });

        warningLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        warningLabel1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout addEnterpriseAdminPanelLayout = new javax.swing.GroupLayout(addEnterpriseAdminPanel);
        addEnterpriseAdminPanel.setLayout(addEnterpriseAdminPanelLayout);
        addEnterpriseAdminPanelLayout.setHorizontalGroup(
            addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEnterpriseAdminPanelLayout.createSequentialGroup()
                .addGroup(addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEnterpriseAdminPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(newEnterpriseLabel1))
                    .addGroup(addEnterpriseAdminPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(addEnterpriseAdminPanelLayout.createSequentialGroup()
                                    .addGroup(addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(addEnterpriseAdminPanelLayout.createSequentialGroup()
                                            .addComponent(enterpriseNameLbl1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEnterpriseAdminPanelLayout.createSequentialGroup()
                                            .addComponent(enterpriseTypeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(enterpriseJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adminNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(addEnterpriseAdminPanelLayout.createSequentialGroup()
                                    .addGroup(addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(enterpriseNameLbl2)
                                        .addComponent(enterpriseNameLbl3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(usernameTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(passwordTextfield))))
                            .addGroup(addEnterpriseAdminPanelLayout.createSequentialGroup()
                                .addComponent(selectNetworkLbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(networkJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addEnterpriseAdminPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(warningLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEnterpriseAdminPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addEnterpriseAdminBtn)
                .addGap(102, 102, 102))
        );
        addEnterpriseAdminPanelLayout.setVerticalGroup(
            addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEnterpriseAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newEnterpriseLabel1)
                .addGap(18, 18, 18)
                .addGroup(addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectNetworkLbl1)
                    .addComponent(networkJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseTypeLbl1)
                    .addComponent(enterpriseJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseNameLbl1)
                    .addComponent(adminNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseNameLbl2)
                    .addComponent(usernameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addEnterpriseAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseNameLbl3)
                    .addComponent(passwordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(addEnterpriseAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        verticalEnterpriseSplitPane.setRightComponent(addEnterpriseAdminPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verticalEnterpriseSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verticalEnterpriseSplitPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseBtnActionPerformed
        // TODO add your handling code here:
        Network network = (Network) networkJComboBox.getSelectedItem();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) enterpriseTypeJComboBox.getSelectedItem();

        if (network == null || type == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }
        if(!nameJTextField.getText().trim().isEmpty() && validator.isValidString(nameJTextField.getText()))
        {
            for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())
            {
                if(enterprise.getName().equals(nameJTextField.getText()))
                {
                    warningLabel.setText("Enterprise name is not available!");
                    return;
                }
            }
            String name = nameJTextField.getText();
            Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);
            populateTable();
            populateEnterpriseComboBox(network);
            nameJTextField.setText("");;
            JOptionPane.showMessageDialog(this,"Enterprise has been created successfully!!","Done",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            warningLabel.setText("*Invalid input");
            nameJTextField.setBackground(Color.pink);
        }
    }//GEN-LAST:event_addEnterpriseBtnActionPerformed

    private void networkComboBoxSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBoxSelected
        // TODO add your handling code here:
        Network network = (Network) networkJComboBox1.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }
    }//GEN-LAST:event_networkComboBoxSelected

    private void addEnterpriseAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseAdminBtnActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
        Role role=null;
        if(enterprise.getEnterpriseType()==Enterprise.EnterpriseType.Healthcare)
        {
            role= new HealthcareAdmin();
        }
        if(enterprise.getEnterpriseType()==Enterprise.EnterpriseType.Meteorological)
        {
            role= new WeatherReporter();
        }
        if(enterprise.getEnterpriseType()==Enterprise.EnterpriseType.Resident)
        {
            role= new ResidentAdmin();
        }
        if(enterprise.getEnterpriseType()==Enterprise.EnterpriseType.TrafficRegulatory)
        {
            role= new TrafficAdmin();
        }
        
        int count=0;
        if(!usernameTextfield.getText().trim().isEmpty() && validator.isValidAlphaNumeric(usernameTextfield.getText().trim()))
        {
            count++;
        }
        else
        {
            usernameTextfield.setBackground(Color.pink);
            warningLabel1.setText("*Invalid input");
        }
        if(!String.valueOf(passwordTextfield.getPassword()).trim().isEmpty())
        {
            count++;
        }
        else
        {
            passwordTextfield.setBackground(Color.pink);
            warningLabel1.setText("*Invalid input");
        }
        if(!adminNameTextfield.getText().trim().isEmpty() && validator.isValidString(adminNameTextfield.getText().trim()))
        {
            count++;
        }
        else
        {
            adminNameTextfield.setBackground(Color.pink);
            warningLabel1.setText("*Invalid input");
        }
        if(count==3)
        {
            if(!enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(usernameTextfield.getText()))
            {
                warningLabel1.setText("Username is not available!");
                return;                
            }
            String username = usernameTextfield.getText();
            String password = String.valueOf(passwordTextfield.getPassword());
            String name = adminNameTextfield.getText();

            Person person = enterprise.getPersonDirectory().createPerson(name);

            UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, person, role);
            populateTable();
            usernameTextfield.setText("");
            passwordTextfield.setText("");
            adminNameTextfield.setText("");
            JOptionPane.showMessageDialog(this,"Admin has been created for "+enterprise+" enterprise!!","Done",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_addEnterpriseAdminBtnActionPerformed

    private void focusGainedToNameTextfield(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedToNameTextfield
        // TODO add your handling code here:
        warningLabel.setText("");
        validator.clearValidationMarkOnFocus(evt);
    }//GEN-LAST:event_focusGainedToNameTextfield

    private void focusGainedToAddAdminTextfields(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGainedToAddAdminTextfields
        // TODO add your handling code here:
        warningLabel1.setText("");
        validator.clearValidationMarkOnFocus(evt);
    }//GEN-LAST:event_focusGainedToAddAdminTextfields

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnterpriseAdminBtn;
    private javax.swing.JPanel addEnterpriseAdminPanel;
    private javax.swing.JButton addEnterpriseBtn;
    private javax.swing.JTextField adminNameTextfield;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel enterpriseNameLbl;
    private javax.swing.JLabel enterpriseNameLbl1;
    private javax.swing.JLabel enterpriseNameLbl2;
    private javax.swing.JLabel enterpriseNameLbl3;
    private javax.swing.JComboBox enterpriseTypeJComboBox;
    private javax.swing.JLabel enterpriseTypeLbl;
    private javax.swing.JLabel enterpriseTypeLbl1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JComboBox networkJComboBox1;
    private javax.swing.JLabel newEnterpriseLabel;
    private javax.swing.JLabel newEnterpriseLabel1;
    private javax.swing.JPanel newEnterprisePanel;
    private javax.swing.JPasswordField passwordTextfield;
    private javax.swing.JLabel selectNetworkLbl;
    private javax.swing.JLabel selectNetworkLbl1;
    private javax.swing.JTextField usernameTextfield;
    private javax.swing.JSplitPane verticalEnterpriseSplitPane;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JLabel warningLabel1;
    // End of variables declaration//GEN-END:variables
}
