/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.ResidentAdmin;

import BLL.EcoSystem;
import BLL.Enterprise.Enterprise;
import BLL.Organization.Organization;
import BLL.Person.Person;
import BLL.Person.VitalSign;
import BLL.Role.Role;
import BLL.UserAccount.UserAccount;
import static UI.SmartDriveMain.dB4OUtil;
import static UI.SmartDriveMain.validator;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankur
 */
public class ResidentAdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form ResidentAdminFrame
     */
    EcoSystem system;
    Enterprise enterprise;
    public ResidentAdminFrame(UserAccount account,EcoSystem system, Enterprise enterprise) {
        initComponents();
        welcomeRoleLabel.setText(account.getPerson().getName());
        this.system=system;
        this.enterprise=enterprise;
        
        populateTable();
        populateCombo();
        checkOrganizations();
    }

    private void checkOrganizations()
    {
        Organization.Type type=(Organization.Type)organizationJComboBox.getSelectedItem();
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization.getName().equals(type.getValue()))
            {
                addOrganizationBtn.setEnabled(false);
                warningLabel.setText("Already available in Organization directory!!");
            }
            else
            {
                addOrganizationBtn.setEnabled(true);
                warningLabel.setText("");
            }
        }
        
         
    }
    private void populateCombo(){
        organizationJComboBox.removeAllItems();
        organizationJComboBox.addItem(Organization.Type.Citizen);
        
        organizationJComboBox1.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            organizationJComboBox1.addItem(organization);
        }
    }

    private void populateRoleCombobox(Organization organization)
    {
        roleJComboBox.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            roleJComboBox.addItem(role);
        }
    }
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }
    private void populateUserTable(Organization organization){
        DefaultTableModel model = (DefaultTableModel) organizationUserTable.getModel();
        
        model.setRowCount(0);
        
        for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()){
            Object[] row = new Object[3];
            row[0] = ua.getPerson().getId();
            row[1] = ua.getPerson().getName();
            row[2] = ua.getUsername();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        horizontalSpiltPane = new javax.swing.JSplitPane();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        welcomeRoleLabel = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        manageOrganizationPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        organizationJComboBox = new javax.swing.JComboBox();
        selectOrganizationLbl = new javax.swing.JLabel();
        addOrganizationBtn = new javax.swing.JButton();
        newOrganizationLabel = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        manageUsersPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        organizationUserTable = new javax.swing.JTable();
        selectOrganizationLbl1 = new javax.swing.JLabel();
        enterpriseTypeLbl1 = new javax.swing.JLabel();
        roleJComboBox = new javax.swing.JComboBox();
        enterpriseNameLbl1 = new javax.swing.JLabel();
        personNameTextfield = new javax.swing.JTextField();
        enterpriseNameLbl2 = new javax.swing.JLabel();
        usernameTextfield = new javax.swing.JTextField();
        enterpriseNameLbl3 = new javax.swing.JLabel();
        passwordTextfield = new javax.swing.JPasswordField();
        addUserBtn = new javax.swing.JButton();
        newEnterpriseLabel1 = new javax.swing.JLabel();
        organizationJComboBox1 = new javax.swing.JComboBox();
        warningLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        horizontalSpiltPane.setDividerLocation(100);
        horizontalSpiltPane.setDividerSize(1);
        horizontalSpiltPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        headerLabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(0, 102, 153));
        headerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car.jpg"))); // NOI18N
        headerLabel.setText("Smart Drive");

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.jpg"))); // NOI18N
        logoutBtn.setToolTipText("Logout and Close");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcomeLabel.setText("Welcome to Portal:");

        welcomeRoleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 491, Short.MAX_VALUE)
                        .addComponent(logoutBtn))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomeRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(welcomeRoleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        horizontalSpiltPane.setTopComponent(headerPanel);

        manageOrganizationPanel.setBackground(new java.awt.Color(255, 255, 255));

        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);

        organizationJComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationSelected(evt);
            }
        });

        selectOrganizationLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selectOrganizationLbl.setText("Select Organization Type:");

        addOrganizationBtn.setBackground(new java.awt.Color(255, 255, 255));
        addOrganizationBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addOrganizationBtn.setForeground(new java.awt.Color(0, 102, 153));
        addOrganizationBtn.setText("Add Organization");
        addOrganizationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganizationBtnActionPerformed(evt);
            }
        });

        newOrganizationLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newOrganizationLabel.setText("Add Organization to Enterprise");

        warningLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout manageOrganizationPanelLayout = new javax.swing.GroupLayout(manageOrganizationPanel);
        manageOrganizationPanel.setLayout(manageOrganizationPanelLayout);
        manageOrganizationPanelLayout.setHorizontalGroup(
            manageOrganizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageOrganizationPanelLayout.createSequentialGroup()
                .addGroup(manageOrganizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageOrganizationPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageOrganizationPanelLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(newOrganizationLabel))
                    .addGroup(manageOrganizationPanelLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(addOrganizationBtn))
                    .addGroup(manageOrganizationPanelLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(selectOrganizationLbl)
                        .addGap(38, 38, 38)
                        .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageOrganizationPanelLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        manageOrganizationPanelLayout.setVerticalGroup(
            manageOrganizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageOrganizationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newOrganizationLabel)
                .addGap(18, 18, 18)
                .addGroup(manageOrganizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectOrganizationLbl))
                .addGap(18, 18, 18)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(addOrganizationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Manage Organization", manageOrganizationPanel);

        manageUsersPanel.setBackground(new java.awt.Color(255, 255, 255));

        organizationUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Citizen ID", "Name", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(organizationUserTable);

        selectOrganizationLbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selectOrganizationLbl1.setText("Select Organization:");

        enterpriseTypeLbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterpriseTypeLbl1.setText("Select Role:");

        roleJComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        enterpriseNameLbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterpriseNameLbl1.setText("Person Name:");

        personNameTextfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        personNameTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                personNameTextfieldfocusGainedToAddAdminTextfields(evt);
            }
        });

        enterpriseNameLbl2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterpriseNameLbl2.setText("Username:");

        usernameTextfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextfieldfocusGainedToAddAdminTextfields(evt);
            }
        });

        enterpriseNameLbl3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterpriseNameLbl3.setText("Password:");

        passwordTextfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTextfieldfocusGainedToAddAdminTextfields(evt);
            }
        });

        addUserBtn.setBackground(new java.awt.Color(255, 255, 255));
        addUserBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addUserBtn.setForeground(new java.awt.Color(0, 102, 153));
        addUserBtn.setText("Submit");
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        newEnterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newEnterpriseLabel1.setText("Add Person to Organization");

        organizationJComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        organizationJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationPersonSelected(evt);
            }
        });

        warningLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        warningLabel1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout manageUsersPanelLayout = new javax.swing.GroupLayout(manageUsersPanel);
        manageUsersPanel.setLayout(manageUsersPanelLayout);
        manageUsersPanelLayout.setHorizontalGroup(
            manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUsersPanelLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageUsersPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageUsersPanelLayout.createSequentialGroup()
                        .addComponent(newEnterpriseLabel1)
                        .addGap(320, 320, 320))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageUsersPanelLayout.createSequentialGroup()
                        .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(manageUsersPanelLayout.createSequentialGroup()
                                .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(selectOrganizationLbl1)
                                    .addComponent(enterpriseTypeLbl1))
                                .addGap(29, 29, 29)
                                .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(organizationJComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roleJComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(manageUsersPanelLayout.createSequentialGroup()
                                .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(enterpriseNameLbl2)
                                    .addComponent(enterpriseNameLbl1)
                                    .addComponent(enterpriseNameLbl3))
                                .addGap(26, 26, 26)
                                .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(personNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(warningLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(271, 271, 271))))
            .addGroup(manageUsersPanelLayout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(addUserBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        manageUsersPanelLayout.setVerticalGroup(
            manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUsersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newEnterpriseLabel1)
                .addGap(18, 18, 18)
                .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationJComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectOrganizationLbl1))
                .addGap(18, 18, 18)
                .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseTypeLbl1))
                .addGap(18, 18, 18)
                .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseNameLbl1)
                    .addComponent(personNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseNameLbl2))
                .addGap(18, 18, 18)
                .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterpriseNameLbl3))
                .addGap(18, 18, 18)
                .addComponent(warningLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(addUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        tabbedPane.addTab("Manage Users", manageUsersPanel);

        horizontalSpiltPane.setRightComponent(tabbedPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(horizontalSpiltPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(horizontalSpiltPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        dB4OUtil.storeSystem(system);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void addOrganizationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganizationBtnActionPerformed
        // TODO add your handling code here:
        Organization.Type type = (Organization.Type) organizationJComboBox.getSelectedItem();
        enterprise.getOrganizationDirectory().createOrganization(type);
        populateTable();
        checkOrganizations();
    }//GEN-LAST:event_addOrganizationBtnActionPerformed

    private void organizationSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationSelected
        // TODO add your handling code here:
        checkOrganizations();
    }//GEN-LAST:event_organizationSelected

    private void personNameTextfieldfocusGainedToAddAdminTextfields(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_personNameTextfieldfocusGainedToAddAdminTextfields
        // TODO add your handling code here:
        warningLabel1.setText("");
        validator.clearValidationMarkOnFocus(evt);
    }//GEN-LAST:event_personNameTextfieldfocusGainedToAddAdminTextfields

    private void usernameTextfieldfocusGainedToAddAdminTextfields(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextfieldfocusGainedToAddAdminTextfields
        // TODO add your handling code here:
        warningLabel1.setText("");
        validator.clearValidationMarkOnFocus(evt);
    }//GEN-LAST:event_usernameTextfieldfocusGainedToAddAdminTextfields

    private void passwordTextfieldfocusGainedToAddAdminTextfields(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextfieldfocusGainedToAddAdminTextfields
        // TODO add your handling code here:
        warningLabel1.setText("");
        validator.clearValidationMarkOnFocus(evt);
    }//GEN-LAST:event_passwordTextfieldfocusGainedToAddAdminTextfields

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        // TODO add your handling code here:
        Organization organization=(Organization)organizationJComboBox1.getSelectedItem();
        Role role = (Role)roleJComboBox.getSelectedItem();

        int count=0;
        if(!usernameTextfield.getText().trim().isEmpty() && validator.isValidAlphaNumeric(usernameTextfield.getText().trim()))
        {
            count++;
        }
        else
        {
            usernameTextfield.setBackground(Color.pink);
            warningLabel1.setText("*Invalid input");
        }
        if(!String.valueOf(passwordTextfield.getPassword()).trim().isEmpty())
        {
            count++;
        }
        else
        {
            passwordTextfield.setBackground(Color.pink);
            warningLabel1.setText("*Invalid input");
        }
        if(!personNameTextfield.getText().trim().isEmpty() && validator.isValidString(personNameTextfield.getText().trim()))
        {
            count++;
        }
        else
        {
            personNameTextfield.setBackground(Color.pink);
            warningLabel1.setText("*Invalid input");
        }
        if(count==3)
        {
            if(!organization.getUserAccountDirectory().checkIfUsernameIsUnique(usernameTextfield.getText()))
            {
                warningLabel1.setText("Username is not available!");
                return;
            }
            String username = usernameTextfield.getText();
            String password = String.valueOf(passwordTextfield.getPassword());
            String name = personNameTextfield.getText();

            Person person=organization.getPersonDirectory().createPerson(name);
            organization.getUserAccountDirectory().createUserAccount(username, password, person, role);
            
            populateUserTable(organization);
            usernameTextfield.setText("");
            passwordTextfield.setText("");
            personNameTextfield.setText("");
            JOptionPane.showMessageDialog(this,"User account has been created for "+person+"!!","Done",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void organizationPersonSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationPersonSelected
        // TODO add your handling code here:
        populateUserTable((Organization)organizationJComboBox1.getSelectedItem());
        populateRoleCombobox((Organization)organizationJComboBox1.getSelectedItem());
    }//GEN-LAST:event_organizationPersonSelected

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrganizationBtn;
    private javax.swing.JButton addUserBtn;
    private javax.swing.JLabel enterpriseNameLbl1;
    private javax.swing.JLabel enterpriseNameLbl2;
    private javax.swing.JLabel enterpriseNameLbl3;
    private javax.swing.JLabel enterpriseTypeLbl1;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JSplitPane horizontalSpiltPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel manageOrganizationPanel;
    private javax.swing.JPanel manageUsersPanel;
    private javax.swing.JLabel newEnterpriseLabel1;
    private javax.swing.JLabel newOrganizationLabel;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JComboBox organizationJComboBox1;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JTable organizationUserTable;
    private javax.swing.JPasswordField passwordTextfield;
    private javax.swing.JTextField personNameTextfield;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JLabel selectOrganizationLbl;
    private javax.swing.JLabel selectOrganizationLbl1;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField usernameTextfield;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JLabel warningLabel1;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeRoleLabel;
    // End of variables declaration//GEN-END:variables
}
